### ISSUE TITLE
submit returns void future

### ISSUE THREAD

**Issue by musketyr** [basejump/grails-executor#12]
If I submit a `Callable` (i.e. `Closure`) to the `executorService`, the right method is called on `PersistenceContextExecutorWrapper` but following code

```
	public <T> Future<T> submit(Callable<T> task) {
		executor.submit(inPersistence(task))
	}
```

will submit to underlaying `executor` as `Runnable` causing the returned `Future` to always return `null`. it should be enough to rewrite it as follows

```
	public <T> Future<T> submit(Callable<T> task) {
		executor.submit(inPersistence(task) as Callable<T>)
	}
```

To guarantee picking the right method.

**Comment by basejump** [comment]
fixed https://github.com/basejump/grails-executor/commit/ff01db34c9a2532624e04c684f11aae9b70b949a
