### ISSUE TITLE
Q: Does this work with Grails 3?

### ISSUE THREAD

**Issue by thomashan** [basejump/grails-executor#13]

**Comment by peh** [comment]
as soon as it is migrated. as it looks like the original author is not maintaining it anymore i will take a look

**Comment by thomashan** [comment]
I will try to look into this as well then. Thanks for commenting.

**Comment by peh** [comment]
as the codebase of this plugin is super small it should be fairly easy

**Comment by bp-FLN** [comment]
Hey @thomashan 

i migrated the plugin to grails3. Please have a look here: https://github.com/uberall/grails-executor

**Comment by basejump** [comment]
This is not really needed for Grails 3. 
See the chapter on Asynchronous Programming
http://docs.grails.org/latest/guide/async.html
